spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mariadb://localhost:3306/predata_question
    username: root
    password: ${DB_PASSWORD:predata}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8082

services:
  blockchain:
    url: http://localhost:8087

logging:
  level:
    com.predata.question: DEBUG
